### ISSUE TITLE
Errors with jar file

### ISSUE THREAD

**Issue by BoltMaud** [lip6/pnmlframework#14]
Hello, 
I tried to use the tool to validate pnml files and I got the following error :

```Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/MimetypesFileTypeMap
        at fr.lip6.move.pnml.validation.impl.CheckPnmlFileImpl.checkPnmlFile(CheckPnmlFileImpl.java:194)
        at fr.lip6.move.pnml.validation.ValidationMain.standalone(ValidationMain.java:268)
        at fr.lip6.move.pnml.validation.ValidationMain.parseArgs(ValidationMain.java:165)
        at fr.lip6.move.pnml.validation.ValidationMain.main(ValidationMain.java:130)
Caused by: java.lang.ClassNotFoundException: javax.activation.MimetypesFileTypeMap
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 4 more
```
I tried several jar file which are available here : http://pnml.lip6.fr/pnmlvalidation/download.html

Best, 
Mathilde

**Comment by yanntm** [comment]
Hi,
Sorry you need a JRE < 11 for pnmlFW to run correctly.
This javax.activation stuff has been removed from recent Java, starting from Java 11.
We recommend using Java 8 currently.

**Comment by BoltMaud** [comment]
Hi, 
Thank you very much, 
Mathilde
